# Numpy

NumPy is a module for Python. The name is an acronym for "Numeric Python" or "Numerical Python". It is pronounced /ˈnʌmpaɪ/ (NUM-py) or less often /ˈnʌmpi (NUM-pee)). It is an extension module for Python, mostly written in C. This makes sure that the precompiled mathematical and numerical functions and functionalities of Numpy guarantee great execution speed.

Furthermore, NumPy enriches the programming language Python with powerful data structures, implementing multi-dimensional arrays and matrices. These data structures guarantee efficient calculations with matrices and arrays. The implementation is even aiming at huge matrices and arrays, better know under the heading of "big data". Besides that the module supplies a large library of high-level mathematical functions to operate on these matrices and arrays.

In [1]:
import numpy as np

In [7]:
import time
size_of_vec = 1000


def pure_python_version():
    start_time = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    time_taken = time.time() - start_time
    return time_taken


def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

In [8]:
t1 = pure_python_version()
t2 = numpy_version()
print(t1,t2)

#Numpy is in this example faster!")

0.0010089874267578125 0.000993967056274414


## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.



In [10]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [11]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            
           
print(a[0], a[1], a[2])   
a[0] = 5                  
print(a)                  

<class 'numpy.ndarray'>
1 2 3
[5 2 3]


In [12]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
                    
print(b[0, 0], b[0, 1], b[1, 0])
print(b)

1 2 4
[[1 2 3]
 [4 5 6]]


In [13]:
list1 = [1,2,3]
list2 = [1,2,3]
a = np.array([list1,list2])
print(type(a))
a

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [1, 2, 3]])

In [14]:
a = np.zeros((2,2))   
print(a)              
print(type(a))                    

# b = np.ones((2,3))    
# print(b)              

# c = np.full((2,2), 1)  
# print(c)               
                       

d = np.eye(3)         
print(d)              
                      

# e = np.random.random((2,2))  
# print(e)     

# f = np.arange(1, 10)
# print(f)
# type(f)
g = np.linspace(1,10,5)
print(g)

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1.    3.25  5.5   7.75 10.  ]


In [17]:
a.shape

(2, 2)

In [18]:
demo = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
demo

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
demo[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [22]:
demo[0,0]

1

In [26]:
demo

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
slice_demo = demo[:,1:2]
print(slice_demo.shape)
slice_demo

(3, 1)


array([[ 2],
       [ 6],
       [10]])

In [25]:
demo>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
demo[demo>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [28]:
X = np.array(range(24))
print(X.shape)
Y = X.reshape((6,4))
print(Y.shape)
Y

(24,)
(6, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
a

array([[0., 0.],
       [0., 0.]])

In [30]:
np.hstack((a,a))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.vstack((a,a))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))



[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [33]:

print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [34]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


---